# Generated by Django 2.1.7 on 2019-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10000)),
                ('features', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
