# Generated by Django 2.1.7 on 2019-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default=property, max_length=250),
            preserve_default=False,
        ),
    ]
