# Generated by Django 2.1.7 on 2019-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0002_property_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Property Title', max_length=250),
        ),
    ]
