# Generated by Django 2.1.7 on 2019-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0003_auto_20190227_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
